#!/bin/bash
# domain info

domain_information() {
    domain=$1
    subdomain=$2
    query_result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
    record_info=$(echo "$query_result" | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$subdomain $record_info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi
