#!/usr/bin/env bash
# install and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy
# load balance server 1 and 2
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 485790-web-01 54.89.116.199:80 check
   server 485790-web-02 54.173.38.154:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
