#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

count=0

# Use a while loop to display "Best School" until count reaches 10
while [ $count -lt 10 ]; do
  echo "Best School"
  ((count++))
done
