#!/usr/bin/env bash
# This script displays numbers and special messages for certain iterations

count=1

# Use a while loop to display numbers and special messages
while [ $count -le 20 ]; do
  case $count in
    4)
      echo "$count"
      echo "bad luck from China"
      ;;
    9)
      echo "$count"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$count"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
  esac
  ((count++))
done
