#!/usr/bin/env bash
# This script lists files in the current directory with names after the first dash

# Use a for loop to iterate over files in the current directory
list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
