#!/usr/bin/env bash
# Run Nginx as Nginx

sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx restart
